// Generated by CoffeeScript 1.4.0
var IDBSchema, Schema;

IDBSchema = window.IDBSchema = {
  describe: function(id) {
    return new Schema(id);
  }
};

Schema = (function() {

  function Schema(id) {
    this.id = id;
    this.migrations = [];
  }

  Schema.prototype.migrate = function(migration) {
    this.migrations.push(migration);
    return this;
  };

  Schema.prototype.createStore = function(name) {
    var createStoreMigration;
    createStoreMigration = function(transaction) {
      return transaction.createObjectStore(name);
    };
    this.migrate(createStoreMigration);
    return this;
  };

  return Schema;

})();
